version: '3.0'

services:

  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx
    hostname: nginx
    ports:
      - "8000:80"

  node1:
    image: nginx:1.27.0-alpine
    container_name: node1
    hostname: node1
    ports:
      - "80"

  node2:
    image: nginx:1.27.0-alpine
    container_name: node2
    hostname: node2
    ports:
      - "80"